spring:
  datasource:
    url: jdbc:postgresql://ep-wandering-wave-agar44l3-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: 
    password: yourpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # or update/create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        # REMOVE dialect: org.hibernate.dialect.PostgreSQLDialect
